# Generated by Django 2.2.1 on 2019-05-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrices',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(max_length=200)),
                ('seller', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'product_prices',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='motherboardprices',
            name='id',
        ),
        migrations.RemoveField(
            model_name='processorprices',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ramprices',
            name='id',
        ),
        migrations.DeleteModel(
            name='GpuPrices',
        ),
        migrations.DeleteModel(
            name='MotherboardPrices',
        ),
        migrations.DeleteModel(
            name='ProcessorPrices',
        ),
        migrations.DeleteModel(
            name='RamPrices',
        ),
    ]
